# JobDSL definition of the seed-job.
# This job creates all other jobs from a Bitbucket repository.
# With this mechanism, it is possible to have a simple job definition in your VCS and there is no need to make
# backups of the jobs. Simply redeploy Jenkins and everything runs as before.
# This job will also be used to add/delete jobs by simply adding new job definitions to the job file in this repository.
jobs:
  - script: >
      job('seed_job') {
          label('jenkins-master')
          multiscm {
              git {
                  remote {
                      url('https://github.com/ibrolive/cloud-devops.git')
                  }
              }
          }
          steps {
              dsl {
                  lookupStrategy('PROVISIONING')
                  external('2. terraform-application-servers/PROVISIONING.Jenkinsfile')
              }
              dsl {
                  lookupStrategy('CI-CD')
                  external('job.groovy')
              }
          }
          triggers {
              scm('* * * * *')
          }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "dockerImageRegistry"
              username: "${DOCKER_IMAGE_REGISTRY_USERNAME:your-username}"
              password: "${DOCKER_IMAGE_REGISTRY_PASSWORD:your-password}"
              description: "Username/password credentials for docker image registry"