# JobDSL definition of the seed-job.
# This job creates all other jobs from a Bitbucket repository.
# With this mechanism, it is possible to have a simple job definition in your VCS and there is no need to make
# backups of the jobs. Simply redeploy Jenkins and everything runs as before.
# This job will also be used to add/delete jobs by simply adding new job definitions to the job file in this repository.
jobs:
  - script: >
      job('seed_job') {
          label('jenkins-master')
          multiscm {
              git {
                  remote {
                      url('https://github.com/ibrolive/cloud-devops.git')
                  }
              }
          }
          steps {
              jobDsl {
                  targets 'job.groovy'
              }
          }
          triggers {
              scm('* * * * *')
          }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "jcasc-credential"
              username: "your-username"
              password: "your-encrypted-password"
              description: "Unused username/password credentials created by JCasC for demo"